---

shared_default: &shared_default
  adapter: postgresql
  encoding: unicode

development:
  <<: *shared_default
  host: localhost
  username: postgres
  password:
  database: personal-pm-project
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *shared_default
  host: <%= ENV['CI'].present? ? 'postgres' : 'localhost' %>
  username: postgres
  password:
  database: personal-pm-project-test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
